### ISSUE TITLE
Support ESlint 4.0

### ISSUE THREAD

**Issue by jscharett** [mysticatea/eslint-plugin-eslint-comments#1]
Looks like 4.0 has some breaking changes as it no longer supports LineComment and BlockComment events.  Any plans on supporting 4.0?

**Comment by mysticatea** [comment]
Thank you for the report!

I have not realized it since I have not upgraded ESLint to 4.0 yet by peerDependencies problems.
I'll fix it.

**Comment by jscharett** [comment]
Seems that rules no-use and no-unlimited-disable are throwing errors when running.  Getting "Warning: Invalid location Use --force to continue" in the console when those rules are enabled.  I'm using eslint 4.0 with grunt-eslint.

**Comment by mysticatea** [comment]
It's not a problem of this plugin. ESLint itself should work with the location.

**Comment by jscharett** [comment]
Looks like its an incompatability between this plugin and the eslint-plugin-html.  In your utils.toForceLocation method, you return a column value of -1 and the html plugin is checking for a 'valid' column value in its TransformableString.locationToIndex method.  Whats the reason for returning a column value of -1?

**Comment by mysticatea** [comment]
Because it's necessary. The reports of `no-unlimited-disable` can exist on the line of `//eslint-disable-line`. In that case, the reports don't work since the line has been disabled. So the rule needs to avoid the disabling of directive comments.
ESLint itself allows the negative locations.
