### ISSUE TITLE
Linting broken in Webstorm

### ISSUE THREAD

**Issue by teux** [mysticatea/eslint-plugin-eslint-comments#14]
Hello,

After updating to eslint-plugin-eslint-comments@3.0.0 I have a problem in Webstorm 2018.1.5

```
Error: Cannot find module '/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/'
Referenced from: /Users/akopersky/WebstormProjects/WebCC/tools/eslint-config-base/index.js
Referenced from: /Users/akopersky/WebstormProjects/WebCC/tools/eslint-config-web/index.js
Referenced from: /Users/akopersky/WebstormProjects/WebCC/tools/eslint-config-react/index.js
Referenced from: /Users/akopersky/WebstormProjects/WebCC/applications/alta-go-cc/src/main/.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Array.from.map.eslintPath (/Users/akopersky/WebstormProjects/WebCC/node_modules/eslint-plugin-eslint-comments/lib/internal/get-linters.js:18:54)
```

I dont know if this problem on Webstorm side. But temporary I fix it wit this code in https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/lib/internal/get-linters.js#L13

`.filter(id => !id.includes('WebStorm.app'))`

**Comment by eugene-malashkin** [comment]
I have the same problem in WebStorm 2018.1.5

**Comment by mysticatea** [comment]
Thank you for this report.

That error log was very helpful. Indeed, this plugin gets loaded module that that path includes `/eslint/`.

I made a PR to fix this: #15, but I don't have WebStorm license.
Would you check whether the PR solved this issue?

```
$ npm install github:mysticatea/eslint-plugin-eslint-comments#fix-for-webstorm
```

**Comment by teux** [comment]
This fix solved the problem

**Comment by eugene-malashkin** [comment]
I am also confirming that the fix solves the problem.
