### ISSUE TITLE
Thank You 🙌🏻

### ISSUE THREAD

**Issue by wcandillon** [mysticatea/eslint-plugin-eslint-comments#16]
I was directed to your plugin through this question: https://stackoverflow.com/questions/50923949/throwing-an-eslint-error-if-disabling-a-rule-that-is-not-triggered/51072005#51072005

Thank you for making this great plugin. Hard to believe it only has 57 stars, should be used by default in every projects :)

You rock 🎸

**Comment by mysticatea** [comment]
Thank you!

Actually, ESLint core features have the `--report-unused-disable-directives` CLI flag which reports unused `eslint-disable` comments. But it's CLI flag, so we cannot configure it in shareable configs. The `eslint-comments/no-unused-disable` rule allows us to enable the CLI flag in shareable configs.
