### ISSUE TITLE
`no-unused-disable` missing in recommended

### ISSUE THREAD

**Issue by e110c0** [mysticatea/eslint-plugin-eslint-comments#22]
while the documentation lists `no-unused-disable` in the recommended section, it is not activated by just using `extends: ['plugin:eslint-comments/recommended']`

Not sure which behaviour is favourable, but config and documentation should match.

**Comment by mysticatea** [comment]
What is "the recommended section"?
The recommended config doesn't include `no-unused-disable` rule intentionally: https://mysticatea.github.io/eslint-plugin-eslint-comments/#%F0%9F%93%96-usage

**Comment by e110c0** [comment]
sorry, didn't write clearly. What I meant is that [`no-unused-disable`](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unused-disable.html) is part of the best practice section in the documentation. Hence I would expect it to be enabled in the `recommended` config.

Not sure how the link explains that it is not included intentionally

**Comment by mysticatea** [comment]
Thank you for the explanation.

"Best Practice" doesn't mean be included in the recommended config. For example, [Core rule list](https://eslint.org/docs/rules/#best-practices) has a ton of best practice rules, but `eslint:recommended` includes a few of those. They indicate the recommended rules by "✔" mark in the list.

Similarly, I indicate the recommended rules by "★" mark in [the rule list](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/).

**Comment by e110c0** [comment]
ah, got it. Sorry I missed that. Thanks for the explanation
