### ISSUE TITLE
new rule: require an explanation comment for all disable directives

### ISSUE THREAD

**Issue by bradzacher** [mysticatea/eslint-plugin-eslint-comments#29]
It's way too easy to disable eslint rules. I don't want to disable them completely though, because sometimes you need to work around a rule.

I'd love to raise the bar so that there must be an explanation comment with the disable.

This makes it easier to review PRs, and means that people can remember why a rule was disabled "way back when" instead of potentially being fixed.

**Comment by mysticatea** [comment]
Thank you for your suggestion.

Sounds a good idea.

**Comment by mysticatea** [comment]
For reference, there is a related RFC: https://github.com/eslint/rfcs/pull/33

**Comment by bradzacher** [comment]
that's an awesome RFC!

**Comment by tuukka** [comment]
Now that the RFC has been implemented in ESLint 7.0.0 and an explanation comment is possible on the same line, should this issue become "new rule: require an explanation comment in disable directives"?
