### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [mysticatea/eslint-plugin-eslint-comments#38]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by dimitropoulos** [comment]
I tested all rules with eslint 7 (with typescript-eslint 3.0.0) and it seemed like every rule worked.

Also, the docs make mention of a new rule that only works with eslint 7 (https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) which makes me think that indicating support for eslint should just be a matter of a formality/added test at this point.

**Comment by MichaelDeBoey** [comment]
Closed by #39
